//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public int CommandID { get; set; }
        public string CommandText { get; set; }
        public int DeviceID { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
