//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int TrackID { get; set; }
        public int DeviceID { get; set; }
        public System.DateTime ReportDateTime { get; set; }
        public System.Data.Spatial.DbGeometry LatLon { get; set; }
        public string Heading { get; set; }
        public string EventCode { get; set; }
        public int Mileage { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
